apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdl-api-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tdl-api
      version: green
  template:
    metadata:
      labels:
        app: tdl-api
        version: green
    spec:
      containers:
        - name: tdl-api
          image: tdl-api:v1.1.1-broken
          ports:
            - containerPort: 5000