apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdl-api-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tdl-api
      version: blue
  template:
    metadata:
      labels:
        app: tdl-api
        version: blue
    spec:
      containers:
        - name: tdl-api
          image: tdl-api:v1.1.0
          ports:
            - containerPort: 5000